version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    image: ridvangulce/user-service:latest
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI_USER_SERVICE}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5001
    depends_on:
      - mongodb

  admin-service:
    build:
      context: ./admin-service
    image: ridvangulce/admin-service:latest
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=${MONGO_URI_ADMIN_SERVICE}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5002
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
