version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    image: ridvangulce/user-service:latest
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  front-end:
    build:
      context: ./front-end
    image: ridvangulce/front-end:latest
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app # Yerel dosyaları Docker içine eşler
      - /app/node_modules # node_modules değişikliğe uğramasın
    environment:
      - NODE_ENV=development
    command: npm run dev # Geliştirme komutunu çalıştırır
    depends_on:
      - user-service

volumes:
  mongo-data:
